server:
  port: 8082

spring:
  application:
    name: gamity-api
  datasource:
    url: jdbc:mysql://db:3306/gamity_db
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    open-in-view: false
